# Generated by Django 4.0.4 on 2022-05-02 16:25

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('street_name', models.CharField(max_length=255, verbose_name='Улица')),
                ('building_number', models.PositiveSmallIntegerField(verbose_name='Номер дома')),
                ('apartment_number', models.PositiveSmallIntegerField(verbose_name='Номер квартиры')),
                ('post_code', models.CharField(max_length=255, verbose_name='Почтовый индекс')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Компания')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('income_per_month', models.PositiveIntegerField(verbose_name='Ежемесячный доход')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('mobile_phone_number', models.CharField(max_length=14, unique=True, verbose_name='Мобильный номер телефона')),
                ('home_phone_number', models.CharField(max_length=14, verbose_name='Домашний номер телефона')),
                ('is_bound_to_military_service', models.BooleanField(blank=True, default=False, null=True, verbose_name='Годен к воинской службе')),
                ('is_disabled', models.BooleanField(blank=True, default=False, null=True, verbose_name='Инвалид')),
                ('is_retiree', models.BooleanField(blank=True, default=False, null=True, verbose_name='Пенсионер')),
                ('address_of_living', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automated_system_statusbank.address')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('iso3code', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True, verbose_name='Код страны')),
                ('country_name', models.CharField(max_length=255, unique=True, verbose_name='Название страны')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование валюты')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.CreateModel(
            name='DepositType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Тип вклада')),
            ],
            options={
                'verbose_name': 'Тип депозита',
                'verbose_name_plural': 'Типы депозитов',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('patronymic', models.CharField(max_length=255, verbose_name='Отчество')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_registration', models.DateField(verbose_name='Дата регистрации')),
                ('registration_authority', models.CharField(max_length=255, verbose_name='Орган выдачи прописки')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automated_system_statusbank.address')),
            ],
            options={
                'verbose_name': 'Прописка',
                'verbose_name_plural': 'Прописки',
            },
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=255, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('series', models.CharField(max_length=255, verbose_name='Серия паспорта')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Номер паспорта')),
                ('date_of_issue', models.DateField(verbose_name='Дата выдачи')),
                ('date_of_expire', models.DateField(verbose_name='Действителен до')),
                ('authority', models.CharField(max_length=255, verbose_name='Орган выдачи паспорта')),
                ('sex', models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], default='Неизвестно', max_length=10, verbose_name='Пол')),
                ('is_married', models.BooleanField(blank=True, default=False, null=True, verbose_name='В браке')),
                ('country_iso3code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='automated_system_statusbank.country')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automated_system_statusbank.registration')),
            ],
            options={
                'verbose_name': 'Паспорт',
                'verbose_name_plural': 'Паспорта',
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.PositiveIntegerField(default=1, unique=True, verbose_name='Номер договора')),
                ('deposit_sum', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Сумма депозита')),
                ('percentage', models.FloatField(verbose_name='Процент')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='automated_system_statusbank.client')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='automated_system_statusbank.currency')),
                ('deposit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automated_system_statusbank.deposittype')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='automated_system_statusbank.worker')),
            ],
            options={
                'verbose_name': 'Депозит',
                'verbose_name_plural': 'Депозиты',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='passport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automated_system_statusbank.passport'),
        ),
        migrations.AddField(
            model_name='address',
            name='country_iso3code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='automated_system_statusbank.country'),
        ),
    ]
