# Generated by Django 4.0.4 on 2022-05-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automated_system_statusbank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='percentage',
            field=models.FloatField(verbose_name='Проценты'),
        ),
    ]
