# Generated by Django 4.0.4 on 2022-05-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automated_system_statusbank', '0002_alter_deposit_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposittype',
            name='description',
            field=models.CharField(default='-', max_length=255, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='deposittype',
            name='type',
            field=models.CharField(choices=[('Безотзывной', 'Безотзывной'), ('Отзывной', 'Отзывной')], default='-', max_length=255, verbose_name='Тип вклада'),
        ),
        migrations.AlterField(
            model_name='deposittype',
            name='name',
            field=models.CharField(default='-', max_length=255, verbose_name='Название'),
        ),
    ]
