# Generated by Django 4.0.4 on 2022-05-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automated_system_statusbank', '0003_deposittype_description_deposittype_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposittype',
            name='description',
            field=models.CharField(default='-', max_length=500, verbose_name='Описание'),
        ),
    ]
