# Generated by Django 4.0.4 on 2022-05-03 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automated_system_statusbank', '0006_deposit_date_of_expire_deposit_date_of_issue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country_iso3code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automated_system_statusbank.country'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automated_system_statusbank.client'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='country_iso3code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automated_system_statusbank.country'),
        ),
    ]
